export default [
  { login: 'abobkov@mail.ru', name: 'Andrey', company: 'Chamomile ltd', active: false },
  { login: 'a-bobkov@my.com', name: 'AnBo', company: 'Chamomile ltd', active: false },
  { login: 'anna.mueller@fintechlab.ch', salutation: 2, name: 'Anna Müller', company: 'FinTech Lab AG', active: true },
  { login: 'luca.rossi@alpinesoft.com', salutation: 1, name: 'Luca Rossi', company: 'AlpineSoft GmbH', active: true },
  { login: 'sophie.dubois@cleardata.io', salutation: 2, name: 'Sophie Dubois', company: 'ClearData Solutions', active: true },
  { login: 'maximilian.weber@nextgen.ai', salutation: 1, name: 'Maximilian Weber', company: 'NextGen AI', active: true },
  { login: 'elena.kovac@bluewave-tech.eu', salutation: 2, name: 'Elena Kovač', company: 'BlueWave Technologies', active: true },
  { login: 'daniel.schmidt@urbancloud.dev', salutation: 1, name: 'Daniel Schmidt', company: 'UrbanCloud', active: true },
  { login: 'irina.popescu@novalink.ro', salutation: 2, name: 'Irina Popescu', company: 'NovaLink Systems', active: true },
  { login: 'thomas.meier@helvetic-digital.ch', salutation: 1, name: 'Thomas Meier', company: 'Helvetic Digital', active: true },
  { login: 'marco.bianchi@cloudnest.it', salutation: 1, name: 'Marco Bianchi', company: 'CloudNest', active: true },
  { login: 'laura.garcia@brightcore.es', salutation: 2, name: 'Laura García', company: 'BrightCore', active: true },
  { login: 'julien.martin@dataspark.fr', salutation: 1, name: 'Julien Martin', company: 'DataSpark', active: true },
  { login: 'emily.johnson@northpeak.io', salutation: 2, name: 'Emily Johnson', company: 'NorthPeak Solutions', active: true },
  { login: 'sebastian.krueger@byteforge.de', salutation: 1, name: 'Sebastian Krüger', company: 'ByteForge', active: true },
  { login: 'nina.petrov@quantix.ai', salutation: 2, name: 'Nina Petrov', company: 'Quantix AI', active: true },
  { login: 'oliver.brown@vertexlabs.co', salutation: 1, name: 'Oliver Brown', company: 'Vertex Labs', active: true },
  { login: 'katarina.jovanovic@softbridge.rs', salutation: 2, name: 'Katarina Jovanović', company: 'SoftBridge', active: true },
  { login: 'henrik.larsen@scaleworks.dk', salutation: 1, name: 'Henrik Larsen', company: 'ScaleWorks', active: true },
  { login: 'isabella.ricci@lumina-tech.it', salutation: 1, name: 'Isabella Ricci', company: 'Lumina Tech', active: true },
  { login: 'pavel.novak@codecraft.cz', salutation: 1, name: 'Pavel Novák', company: 'CodeCraft', active: true },
  { login: 'maya.patel@orbitalsys.com', salutation: 2, name: 'Maya Patel', company: 'Orbital Systems', active: true },
  { login: 'andre.silva@fluxware.pt', salutation: 2, name: 'André Silva', company: 'Fluxware', active: true },
  { login: 'clara.fischer@netwise.ch', salutation: 2, name: 'Clara Fischer', company: 'NetWise', active: true },
  { login: 'tom.williams@skylineapps.io', salutation: 1, name: 'Tom Williams', company: 'Skyline Apps', active: true },
  { login: 'aline.moreau@deepframe.ai', salutation: 2, name: 'Aline Moreau', company: 'DeepFrame AI', active: true },
  { login: 'jakub.kowalski@corestack.pl', salutation: 1, name: 'Jakub Kowalski', company: 'CoreStack', active: true },
  { login: 'sofia.nikolaou@horizonsystems.gr', salutation: 2, name: 'Sofia Nikolaou', company: 'Horizon Systems', active: true },
  { login: 'daniel.huber@stackflow.dev', salutation: 1, name: 'Daniel Huber', company: 'StackFlow', active: true },
  { login: 'rebecca.lee@insightloop.com', salutation: 2, name: 'Rebecca Lee', company: 'InsightLoop', active: true },
  { login: 'rebecca.ups@insightloop.com', salutation: 2, name: 'Rebecca Lee Sr', company: 'InsightLoop', active: true },
];