export default [
  { login: 'abobkov@mail.ru', name: 'Andrey', company: 'Chamomile ltd' },
  { login: 'a-bobkov@my.com', name: 'AnBo', company: 'Chamomile ltd' },
  { login: 'anna.mueller@fintechlab.ch', name: 'Anna Müller', company: 'FinTech Lab AG' },
  { login: 'luca.rossi@alpinesoft.com', name: 'Luca Rossi', company: 'AlpineSoft GmbH'},
  { login: 'sophie.dubois@cleardata.io', name: 'Sophie Dubois', company: 'ClearData Solutions' },
  { login: 'maximilian.weber@nextgen.ai', name: 'Maximilian Weber', company: 'NextGen AI' },
  { login: 'elena.kovac@bluewave-tech.eu', name: 'Elena Kovač', company: 'BlueWave Technologies' },
  { login: 'daniel.schmidt@urbancloud.dev', name: 'Daniel Schmidt', company: 'UrbanCloud' },
  { login: 'irina.popescu@novalink.ro', name: 'Irina Popescu', company: 'NovaLink Systems' },
  { login: 'thomas.meier@helvetic-digital.ch', name: 'Thomas Meier', company: 'Helvetic Digital' },
  { login: 'marco.bianchi@cloudnest.it', name: 'Marco Bianchi', company: 'CloudNest' },
  { login: 'laura.garcia@brightcore.es', name: 'Laura García', company: 'BrightCore' },
  { login: 'julien.martin@dataspark.fr', name: 'Julien Martin', company: 'DataSpark' },
  { login: 'emily.johnson@northpeak.io', name: 'Emily Johnson', company: 'NorthPeak Solutions' },
  { login: 'sebastian.krueger@byteforge.de', name: 'Sebastian Krüger', company: 'ByteForge' },
  { login: 'nina.petrov@quantix.ai', name: 'Nina Petrov', company: 'Quantix AI' },
  { login: 'oliver.brown@vertexlabs.co', name: 'Oliver Brown', company: 'Vertex Labs' },
  { login: 'katarina.jovanovic@softbridge.rs', name: 'Katarina Jovanović', company: 'SoftBridge' },
  { login: 'henrik.larsen@scaleworks.dk', name: 'Henrik Larsen', company: 'ScaleWorks' },
  { login: 'isabella.ricci@lumina-tech.it', name: 'Isabella Ricci', company: 'Lumina Tech' },
  { login: 'pavel.novak@codecraft.cz', name: 'Pavel Novák', company: 'CodeCraft' },
  { login: 'maya.patel@orbitalsys.com', name: 'Maya Patel', company: 'Orbital Systems' },
  { login: 'andre.silva@fluxware.pt', name: 'André Silva', company: 'Fluxware' },
  { login: 'clara.fischer@netwise.ch', name: 'Clara Fischer', company: 'NetWise' },
  { login: 'tom.williams@skylineapps.io', name: 'Tom Williams', company: 'Skyline Apps' },
  { login: 'aline.moreau@deepframe.ai', name: 'Aline Moreau', company: 'DeepFrame AI' },
  { login: 'jakub.kowalski@corestack.pl', name: 'Jakub Kowalski', company: 'CoreStack' },
  { login: 'sofia.nikolaou@horizonsystems.gr', name: 'Sofia Nikolaou', company: 'Horizon Systems' },
  { login: 'daniel.huber@stackflow.dev', name: 'Daniel Huber', company: 'StackFlow' },
  { login: 'rebecca.lee@insightloop.com', name: 'Rebecca Lee', company: 'InsightLoop' },
  { login: 'rebecca.ups@insightloop.com', name: 'Rebecca Lee Sr', company: 'InsightLoop' },
];