export default [
  { login: 'a-bobkov@mail.ru', name: 'Andrey', company: 'Chamomile ltd' },
  { login: 'abobkov@my.com', name: 'AnBo', company: 'Chamomile ltd' },
  { login: 'abobkov@my.com', name: 'AnBo', company: 'Chamomile ltd' },
  { login: 'abobkov@my.com', name: 'AnBo', company: 'Chamomile ltd' },
  { login: 'abobkov@my.com', name: 'AnBo', company: 'Chamomile ltd' },
  { login: 'abobkov@my.com', name: 'AnBo', company: 'Chamomile ltd' },
  { login: 'abobkov@my.com', name: 'AnBo', company: 'Chamomile ltd' },
  { login: 'abobkov@my.com', name: 'AnBo', company: 'Chamomile ltd' },
  { login: 'abobkov@my.com', name: 'AnBo', company: 'Chamomile ltd' },
  { login: 'abobkov@my.com', name: 'AnBo', company: 'Chamomile ltd' },
  { login: 'abobkov@my.com', name: 'AnBo', company: 'Chamomile ltd' },
  { login: 'abobkov@my.com', name: 'AnBo', company: 'Chamomile ltd' },
  { login: 'abobkov@my.com', name: 'AnBo', company: 'Chamomile ltd' },
  { login: 'abobkov@my.com', name: 'AnBo', company: 'Chamomile ltd' },
  { login: 'abobkov@my.com', name: 'AnBo', company: 'Chamomile ltd' },
  { login: 'abobkov@my.com', name: 'AnBo', company: 'Chamomile ltd' },
  { login: 'abobkov@my.com', name: 'AnBo', company: 'Chamomile ltd' },
  { login: 'abobkov@my.com', name: 'AnBo', company: 'Chamomile ltd' },
  { login: 'abobkov@my.com', name: 'AnBo', company: 'Chamomile ltd' },
];