export default [
  { login: 'abobkov@mail.ru', name: 'Andrey', company: 'Chamomile ltd', branch: { id: 2 }, active: false },
  { login: 'a-bobkov@my.com', name: 'AnBo', company: 'Chamomile ltd', branch: { id: 2 }, active: false },
  { login: 'anna.mueller@fintechlab.ch', salutation: { id: 2 }, name: 'Anna Müller', company: 'FinTech Lab AG', branch: { id: 1 }, active: true },
  { login: 'luca.rossi@alpinesoft.com', salutation: { id: 1 }, name: 'Luca Rossi', company: 'AlpineSoft GmbH', branch: { id: 1 }, active: true },
  { login: 'sophie.dubois@cleardata.io', salutation: { id: 2 }, name: 'Sophie Dubois', company: 'ClearData Solutions', branch: { id: 1 }, active: true },
  { login: 'maximilian.weber@nextgen.ai', salutation: { id: 1 }, name: 'Maximilian Weber', company: 'NextGen AI', branch: { id: 1 }, active: true },
  { login: 'elena.kovac@bluewave-tech.eu', salutation: { id: 2 }, name: 'Elena Kovač', company: 'BlueWave Technologies', branch: { id: 1 }, active: true },
  { login: 'daniel.schmidt@urbancloud.dev', salutation: { id: 1 }, name: 'Daniel Schmidt', company: 'UrbanCloud', branch: { id: 1 }, active: true },
  { login: 'irina.popescu@novalink.ro', salutation: { id: 2 }, name: 'Irina Popescu', company: 'NovaLink Systems', branch: { id: 3 }, active: true },
  { login: 'thomas.meier@helvetic-digital.ch', salutation: { id: 1 }, name: 'Thomas Meier', company: 'Helvetic Digital', branch: { id: 3 }, active: true },
  { login: 'marco.bianchi@cloudnest.it', salutation: { id: 1 }, name: 'Marco Bianchi', company: 'CloudNest', branch: { id: 3 }, active: true },
  { login: 'laura.garcia@brightcore.es', salutation: { id: 2 }, name: 'Laura García', company: 'BrightCore', branch: { id: 3 }, active: true },
  { login: 'julien.martin@dataspark.fr', salutation: { id: 1 }, name: 'Julien Martin', company: 'DataSpark', branch: { id: 3 }, active: true },
  { login: 'emily.johnson@northpeak.io', salutation: { id: 2 }, name: 'Emily Johnson', company: 'NorthPeak Solutions', branch: { id: 3 }, active: true },
  { login: 'sebastian.krueger@byteforge.de', salutation: { id: 1 }, name: 'Sebastian Krüger', company: 'ByteForge', branch: { id: 4 }, active: true },
  { login: 'nina.petrov@quantix.ai', salutation: { id: 2 }, name: 'Nina Petrov', company: 'Quantix AI', branch: { id: 4 }, active: true },
  { login: 'oliver.brown@vertexlabs.co', salutation: { id: 1 }, name: 'Oliver Brown', company: 'Vertex Labs', branch: { id: 4 }, active: true },
  { login: 'katarina.jovanovic@softbridge.rs', salutation: { id: 2 }, name: 'Katarina Jovanović', company: 'SoftBridge', branch: { id: 4 }, active: true },
  { login: 'henrik.larsen@scaleworks.dk', salutation: { id: 1 }, name: 'Henrik Larsen', company: 'ScaleWorks', branch: { id: 2 }, active: true },
  { login: 'isabella.ricci@lumina-tech.it', salutation: { id: 1 }, name: 'Isabella Ricci', company: 'Lumina Tech', branch: { id: 2 }, active: true },
  { login: 'pavel.novak@codecraft.cz', salutation: { id: 1 }, name: 'Pavel Novák', company: 'CodeCraft', branch: { id: 2 }, active: true },
  { login: 'maya.patel@orbitalsys.com', salutation: { id: 2 }, name: 'Maya Patel', company: 'Orbital Systems', branch: { id: 2 }, active: true },
  { login: 'andre.silva@fluxware.pt', salutation: { id: 2 }, name: 'André Silva', company: 'Fluxware', branch: { id: 1 }, active: true },
  { login: 'clara.fischer@netwise.ch', salutation: { id: 2 }, name: 'Clara Fischer', company: 'NetWise', branch: { id: 2 }, active: true },
  { login: 'tom.williams@skylineapps.io', salutation: { id: 1 }, name: 'Tom Williams', company: 'Skyline Apps', branch: { id: 3 }, active: true },
  { login: 'aline.moreau@deepframe.ai', salutation: { id: 2 }, name: 'Aline Moreau', company: 'DeepFrame AI', branch: { id: 4 }, active: true },
  { login: 'jakub.kowalski@corestack.pl', salutation: { id: 1 }, name: 'Jakub Kowalski', company: 'CoreStack', branch: { id: 1 }, active: true },
  { login: 'sofia.nikolaou@horizonsystems.gr', salutation: { id: 2 }, name: 'Sofia Nikolaou', company: 'Horizon Systems', branch: { id: 1 }, active: true },
  { login: 'daniel.huber@stackflow.dev', salutation: { id: 1 }, name: 'Daniel Huber', company: 'StackFlow', branch: { id: 2 }, active: true },
  { login: 'rebecca.lee@insightloop.com', salutation: { id: 2 }, name: 'Rebecca Lee', company: 'InsightLoop', branch: { id: 3 }, active: true },
  { login: 'rebecca.ups@insightloop.com', salutation: { id: 2 }, name: 'Rebecca Lee Senior', company: 'InsightLoop', branch: { id: 5 }, active: true },
];